# Generated by Django 5.0.4 on 2024-04-18 04:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='profile',
            options={'ordering': ['-id'], 'verbose_name': 'perfil', 'verbose_name_plural': 'perfiles'},
        ),
    ]
