# Generated by Django 5.0.4 on 2024-04-18 23:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservas', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cabaña',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nomCabaña', models.CharField(max_length=20, verbose_name='Cabaña')),
                ('perMax', models.PositiveIntegerField(default=1, verbose_name='Personas maximas')),
                ('precio', models.FloatField(default=0, verbose_name='Precio')),
                ('descripcion', models.CharField(blank=True, max_length=70, null=True, verbose_name='Descripción')),
                ('imagen', models.ImageField(blank=True, null=True, upload_to='images_Cabañas', verbose_name='Imagen')),
            ],
            options={
                'verbose_name': 'Cabaña',
                'verbose_name_plural': 'Cabañas',
            },
        ),
        migrations.AlterField(
            model_name='categoria',
            name='nomCategoria',
            field=models.CharField(max_length=30, verbose_name='Nombre de la categoria'),
        ),
        migrations.AlterField(
            model_name='estado',
            name='tipEstado',
            field=models.CharField(max_length=15, verbose_name='Tipo de estado'),
        ),
    ]
