# Generated by Django 5.0.4 on 2024-04-18 23:36

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservas', '0002_cabaña_alter_categoria_nomcategoria_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Reserva',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fechaReserva', models.DateField(verbose_name='Fecha de reserva')),
                ('fechaCheckIn', models.DateField(verbose_name='Fecha de check in')),
                ('fechaCheckOut', models.DateField(verbose_name='Fecha de check out')),
                ('cabana', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='reservas.cabaña', verbose_name='Cabaña')),
                ('estado', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='reservas.estado', verbose_name='Estado')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='usuario_reserva', to=settings.AUTH_USER_MODEL, verbose_name='Usuario')),
            ],
            options={
                'verbose_name': 'reserva',
                'verbose_name_plural': 'reservas',
            },
        ),
    ]
