# Generated by Django 5.0.4 on 2024-04-19 00:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservas', '0003_reserva'),
    ]

    operations = [
        migrations.CreateModel(
            name='Metodo_Pago',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nomMetodo', models.CharField(max_length=30, verbose_name='Metodo de pago')),
            ],
            options={
                'verbose_name': 'metodo de pago',
                'verbose_name_plural': 'metodos de pago',
            },
        ),
        migrations.AlterField(
            model_name='reserva',
            name='fechaReserva',
            field=models.DateField(auto_now_add=True, verbose_name='Fecha de reserva'),
        ),
        migrations.CreateModel(
            name='Factura',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total', models.FloatField(default=0, verbose_name='Total')),
                ('Estado', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='reservas.estado', verbose_name='Estado')),
                ('Reserva', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Reserva_factura', to='reservas.reserva', verbose_name='Reserva')),
                ('metodo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='reservas.metodo_pago', verbose_name='Metodo de pago')),
            ],
            options={
                'verbose_name': 'factura',
                'verbose_name_plural': 'facturas',
            },
        ),
        migrations.CreateModel(
            name='Pedido',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fechaHora', models.DateTimeField(auto_now_add=True, verbose_name='Fecha y hora')),
                ('Reserva', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Reserva_pedido', to='reservas.reserva', verbose_name='Reserva')),
                ('estado', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='reservas.estado', verbose_name='Estado')),
            ],
            options={
                'verbose_name': 'pedido',
                'verbose_name_plural': 'pedidos',
            },
        ),
        migrations.CreateModel(
            name='Producto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nomProducto', models.CharField(max_length=30, verbose_name='Nombre del producto')),
                ('precio', models.FloatField(default=0, verbose_name='Precio')),
                ('descripcion', models.CharField(blank=True, max_length=50, null=True, verbose_name='Descripción')),
                ('cantidad', models.PositiveIntegerField(default=1, verbose_name='Cantidad')),
                ('Estado', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='reservas.estado', verbose_name='Estado')),
                ('categoria', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='reservas.categoria', verbose_name='Categoriá')),
            ],
            options={
                'verbose_name': 'producto',
                'verbose_name_plural': 'productos',
            },
        ),
        migrations.CreateModel(
            name='Pedido_Producto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pedido', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='reservas.pedido', verbose_name='Pedido')),
                ('producto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='reservas.producto', verbose_name='producto')),
            ],
            options={
                'verbose_name': 'pedido_proyecto',
                'verbose_name_plural': 'pedidos_proyectos',
            },
        ),
    ]
