# Generated by Django 5.0.4 on 2024-04-19 00:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reservas', '0004_metodo_pago_alter_reserva_fechareserva_factura_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='pedido_producto',
            options={'verbose_name': 'pedido_producto', 'verbose_name_plural': 'pedidos_productos'},
        ),
    ]
