# Generated by Django 5.0.4 on 2024-04-19 00:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservas', '0005_alter_pedido_producto_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='producto',
            name='imagen',
            field=models.ImageField(blank=True, null=True, upload_to='images_productos', verbose_name='Imagen'),
        ),
    ]
