# Generated by Django 5.0.4 on 2024-05-09 03:59

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservas', '0007_reserva_numpersonas'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pedido',
            name='fechaHora',
        ),
        migrations.AddField(
            model_name='pedido_producto',
            name='fechaHora',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now, verbose_name='Fecha y hora'),
            preserve_default=False,
        ),
    ]
