# Generated by Django 5.0.4 on 2024-05-20 01:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservas', '0008_remove_pedido_fechahora_pedido_producto_fechahora'),
    ]

    operations = [
        migrations.AddField(
            model_name='pedido_producto',
            name='cantidad',
            field=models.PositiveIntegerField(default=1, verbose_name='Cantidad'),
        ),
    ]
